<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
	  <groupId>io.ddaaniel</groupId>
	  <artifactId>httpFROMtcp-parent</artifactId>
	  <version>1.0-SNAPSHOT</version>
  </parent>

  <artifactId>http</artifactId>

  <name>httpFROMtcp</name>
  <!-- FIXME change it to the project's website -->
  <url>http://www.example.com</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.release>21</maven.compiler.release>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.junit</groupId>
        <artifactId>junit-bom</artifactId>
        <version>5.11.0</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
	  <dependency>
		  <groupId>io.ddaaniel</groupId>
		  <artifactId>http-processor</artifactId>
		  <version>1.0-SNAPSHOT</version>
		  <scope>provided</scope> </dependency>

	  <dependency>
		  <groupId>org.junit.jupiter</groupId>
		  <artifactId>junit-jupiter-api</artifactId>
		  <scope>test</scope>
	  </dependency>
	  <!-- Optionally: parameterized tests support -->
	  <dependency>
		  <groupId>org.junit.jupiter</groupId>
		  <artifactId>junit-jupiter-params</artifactId>
		  <scope>test</scope>
	  </dependency>
	  <dependency>
		  <groupId>org.mockito</groupId>
		  <artifactId>mockito-core</artifactId>
		  <version>5.20.0</version>
		  <scope>test</scope>
	  </dependency>
  </dependencies>

  <build>
	  <plugins>
		  <plugin>
			  <groupId>org.apache.maven.plugins</groupId>
			  <artifactId>maven-jar-plugin</artifactId>
			  <version>3.4.2</version>
			  <configuration>
				  <archive>
					  <manifest>
						  <addClasspath>true</addClasspath>
						  <mainClass>io.ddaaniel.Main</mainClass>
					  </manifest>
				  </archive>
			  </configuration>
		  </plugin>

		  <plugin>
			  <groupId>org.apache.maven.plugins</groupId>
			  <artifactId>maven-compiler-plugin</artifactId>
			  <version>3.13.0</version>
			  <configuration>
				  <annotationProcessorPaths>
					  <path>
						  <groupId>io.ddaaniel</groupId>
						  <artifactId>http-processor</artifactId>
						  <version>1.0-SNAPSHOT</version>
					  </path>
				  </annotationProcessorPaths>
				  <generatedSourcesDirectory>${project.build.directory}/generated-sources/annotations</generatedSourcesDirectory>
			  </configuration>
		  </plugin>

		  <plugin>
			  <groupId>org.graalvm.buildtools</groupId>
			  <artifactId>native-maven-plugin</artifactId>
			  <version>0.10.2</version>
			  <executions>
				  <execution>
					  <id>build-native</id>
					  <goals>
						  <goal>compile-no-fork</goal>
					  </goals>
					  <phase>package</phase>
				  </execution>
			  </executions>
			  <configuration>
				  <imageName>httpfromtcp-teste</imageName>
				  <mainClass>io.ddaaniel.Main</mainClass> 
				  <buildArgs>
					  <buildArg>-O4</buildArg>
					  <buildArg>--no-fallback</buildArg>
				  </buildArgs>
			  </configuration>
		  </plugin>
	  </plugins>
  </build>
</project>
